[2024-04-22T00:00:18.792+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_heart_data.make_dummies_variables scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T00:00:18.797+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_heart_data.make_dummies_variables scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T00:00:18.798+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-22T00:00:18.805+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): make_dummies_variables> on 2024-04-21 00:00:00+00:00
[2024-04-22T00:00:18.809+0000] {standard_task_runner.py:60} INFO - Started process 3773 to run task
[2024-04-22T00:00:18.811+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_heart_data', 'make_dummies_variables', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpve518i69']
[2024-04-22T00:00:18.812+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask make_dummies_variables
[2024-04-22T00:00:18.844+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_heart_data.make_dummies_variables scheduled__2024-04-21T00:00:00+00:00 [running]> on host 3ab9e2e1209e
[2024-04-22T00:00:18.890+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='process_etl_heart_data' AIRFLOW_CTX_TASK_ID='make_dummies_variables' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T00:00:18.891+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvmb3f5nn3 --system-site-packages --python=python
[2024-04-22T00:00:18.899+0000] {process_utils.py:186} INFO - Output:
[2024-04-22T00:00:19.811+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 615ms
[2024-04-22T00:00:19.811+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvmb3f5nn3, clear=False, no_vcs_ignore=False, global=True)
[2024-04-22T00:00:19.812+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-22T00:00:19.812+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-22T00:00:19.812+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-22T00:00:19.835+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvmb3f5nn3/bin/pip install -r /tmp/venvmb3f5nn3/requirements.txt
[2024-04-22T00:00:19.840+0000] {process_utils.py:186} INFO - Output:
[2024-04-22T00:00:21.180+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvmb3f5nn3/requirements.txt (line 1))
[2024-04-22T00:00:21.182+0000] {process_utils.py:190} INFO -   Using cached awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-22T00:00:21.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (1.34.88)
[2024-04-22T00:00:21.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (1.34.88)
[2024-04-22T00:00:21.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (1.24.4)
[2024-04-22T00:00:21.216+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (23.2)
[2024-04-22T00:00:21.216+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (2.0.3)
[2024-04-22T00:00:21.217+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (14.0.2)
[2024-04-22T00:00:21.218+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (4.9.0)
[2024-04-22T00:00:21.221+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (0.10.0)
[2024-04-22T00:00:21.222+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (0.10.1)
[2024-04-22T00:00:21.226+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (2.8.2)
[2024-04-22T00:00:21.227+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (1.26.18)
[2024-04-22T00:00:21.284+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (2023.3.post1)
[2024-04-22T00:00:21.284+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (2023.4)
[2024-04-22T00:00:21.289+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvmb3f5nn3/requirements.txt (line 1)) (1.16.0)
[2024-04-22T00:00:21.309+0000] {process_utils.py:190} INFO - Using cached awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-22T00:00:23.223+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2024-04-22T00:00:23.585+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0
[2024-04-22T00:00:23.728+0000] {process_utils.py:190} INFO - 
[2024-04-22T00:00:23.728+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-22T00:00:23.729+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-22T00:00:23.856+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvmb3f5nn3/bin/python /tmp/venv-callgcjhsl9z/script.py /tmp/venv-callgcjhsl9z/script.in /tmp/venv-callgcjhsl9z/script.out /tmp/venv-callgcjhsl9z/string_args.txt /tmp/venv-callgcjhsl9z/termination.log
[2024-04-22T00:00:23.863+0000] {process_utils.py:186} INFO - Output:
[2024-04-22T00:00:25.487+0000] {process_utils.py:190} INFO - [[34m2024-04-22T00:00:25.486+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-22T00:00:25.618+0000] {process_utils.py:190} INFO - [[34m2024-04-22T00:00:25.617+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-22T00:00:25.659+0000] {process_utils.py:190} INFO - [[34m2024-04-22T00:00:25.658+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-22T00:00:25.692+0000] {process_utils.py:190} INFO - [[34m2024-04-22T00:00:25.692+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-22T00:00:25.867+0000] {process_utils.py:190} INFO - [[34m2024-04-22T00:00:25.867+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-22T00:00:25.903+0000] {process_utils.py:190} INFO - [[34m2024-04-22T00:00:25.903+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-22T00:00:26.047+0000] {process_utils.py:190} INFO - 2024/04/22 00:00:26 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2024-04-22T00:00:26.048+0000] {process_utils.py:190} INFO - The git executable must be specified in one of the following ways:
[2024-04-22T00:00:26.048+0000] {process_utils.py:190} INFO -     - be included in your $PATH
[2024-04-22T00:00:26.048+0000] {process_utils.py:190} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2024-04-22T00:00:26.048+0000] {process_utils.py:190} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2024-04-22T00:00:26.049+0000] {process_utils.py:190} INFO - 
[2024-04-22T00:00:26.049+0000] {process_utils.py:190} INFO - All git commands will error until this is rectified.
[2024-04-22T00:00:26.049+0000] {process_utils.py:190} INFO - 
[2024-04-22T00:00:26.049+0000] {process_utils.py:190} INFO - This initial message can be silenced or aggravated in the future by setting the
[2024-04-22T00:00:26.049+0000] {process_utils.py:190} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2024-04-22T00:00:26.050+0000] {process_utils.py:190} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2024-04-22T00:00:26.050+0000] {process_utils.py:190} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2024-04-22T00:00:26.050+0000] {process_utils.py:190} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2024-04-22T00:00:26.050+0000] {process_utils.py:190} INFO - 
[2024-04-22T00:00:26.050+0000] {process_utils.py:190} INFO - Example:
[2024-04-22T00:00:26.051+0000] {process_utils.py:190} INFO -     export GIT_PYTHON_REFRESH=quiet
[2024-04-22T00:00:26.051+0000] {process_utils.py:190} INFO - 
[2024-04-22T00:00:26.368+0000] {process_utils.py:190} INFO - 2024/04/22 00:00:26 WARNING mlflow.system_metrics.system_metrics_monitor: Skip logging GPU metrics because creating `GPUMonitor` failed with error: `pynvml` is not installed, to log GPU metrics please run `pip install pynvml` to install it..
[2024-04-22T00:00:26.369+0000] {process_utils.py:190} INFO - 2024/04/22 00:00:26 INFO mlflow.system_metrics.system_metrics_monitor: Started monitoring system metrics.
[2024-04-22T00:00:26.499+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:150 UserWarning: Failed to determine whether UCVolumeDatasetSource can resolve source information for 'https://archive.ics.uci.edu/dataset/45/heart+disease'. Exception:
[2024-04-22T00:00:26.504+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:150 UserWarning: Failed to determine whether UCVolumeDatasetSource can resolve source information for 'https://archive.ics.uci.edu/dataset/45/heart+disease'. Exception:
[2024-04-22T00:00:26.509+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:394 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2024-04-22T00:00:26.563+0000] {process_utils.py:190} INFO - 2024/04/22 00:00:26 INFO mlflow.system_metrics.system_metrics_monitor: Stopping system metrics monitoring...
[2024-04-22T00:00:26.579+0000] {process_utils.py:190} INFO - 2024/04/22 00:00:26 INFO mlflow.system_metrics.system_metrics_monitor: Successfully terminated system metrics monitoring!
[2024-04-22T00:00:26.914+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-22T00:00:26.924+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_heart_data, task_id=make_dummies_variables, execution_date=20240421T000000, start_date=20240422T000018, end_date=20240422T000026
[2024-04-22T00:00:26.954+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T00:00:26.972+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
